# Generated by Django 5.2 on 2025-05-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('ano', models.DateField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
