# Generated by Django 5.2 on 2025-05-08 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('autor', models.CharField(blank=True, max_length=150, null=True)),
                ('subAreas', models.CharField(blank=True, max_length=150, null=True)),
                ('dataPublicacao', models.DateField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='ESource.evento')),
            ],
        ),
    ]
