# Generated by Django 5.2 on 2025-05-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0002_artigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ano',
            new_name='data',
        ),
    ]
