# Generated by Django 5.2 on 2025-05-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0003_rename_ano_evento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('objetoId', models.PositiveIntegerField()),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('modelo', 'objetoId')},
            },
        ),
    ]
