# Generated by Django 5.2 on 2025-05-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0005_autor_alter_status_options_remove_artigo_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='status',
            field=models.CharField(choices=[('DISP', 'Disponível'), ('ARQ', 'Arquivado')], default='DISP', max_length=4),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('DISP', 'Disponível'), ('ARQ', 'Arquivado')], default='DISP', max_length=4),
        ),
    ]
