# Generated by Django 5.2 on 2025-05-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0006_artigo_status_evento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autores', 'verbose_name_plural': 'Autores'},
        ),
    ]
