# Generated by Django 5.2 on 2025-05-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0007_alter_autor_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='imagem',
        ),
    ]
