# Generated by Django 5.2.1 on 2025-05-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESource', '0008_remove_artigo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='instituicao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='unidade_federativa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
